import { Edit } from '../../domain/edit/Edit';
import { ValidationError } from '../../domain/common/errors';

export class CreateEdit {
  constructor(editsRepo) {
    this._editsRepo = editsRepo;
  }

  exec = async (edit) => {
    if (!edit) throw new ValidationError('An edit is required');

    const newEdit = { ...edit };

    if (!newEdit.id)
      newEdit.id = await this._editsRepo.nextId(newEdit.scriptId);
    if (!newEdit.createdAt) newEdit.createdAt = new Date();

    const editEntity = Edit.create(newEdit);

    const savedEdit = await this._editsRepo.save(editEntity);

    // savedEdit will contain the script with the id generated by the database
    return savedEdit || editEntity;
  };
}
