import { Edit } from '../edit/Edit';
import { ValidationError } from '../common/errors';

export class Script {
  constructor({ id, content, createdAt, title, userId, edits = [] }) {
    this._id = id;
    this._content = content;
    this._createdAt = createdAt;
    this._title = title;
    this._userId = userId;
    this._edits = edits;
  }

  static create({ id, content = '', createdAt, title, userId, edits = [] }) {
    if (!id) throw new ValidationError('Script: id is required');
    if (typeof id !== 'number')
      throw new ValidationError('Script: id must be a number');
    if (!createdAt) throw new ValidationError('Script: createdAt is required');
    if (!title) throw new ValidationError('Script: title is required');
    if (!userId) throw new ValidationError('Script: userId is required');

    if (!(createdAt instanceof Date) || isNaN(createdAt.getTime()))
      throw new ValidationError('createdAt must be a valid date');

    if (!Array.isArray(edits))
      throw new ValidationError('Script: edits must be an array');

    for (const edit of edits) {
      if (!(edit instanceof Edit))
        throw new ValidationError(
          'Script: edits must contain objects of type Edit'
        );
    }

    return new Script({ id, content, createdAt, title, userId, edits });
  }

  update({ title, content } = {}) {
    if (title) this._updateTitle(title);
    if (content) this._updateContent(content);

    return this;
  }

  addEdit(edit) {
    if (!(edit instanceof Edit)) {
      throw new ValidationError('edit must be an instance of Edit');
    }
    this._edits.push(edit);
  }

  removeEdit(editId) {
    const editIndex = this._edits.findIndex((edit) => edit.id === editId);
    if (editIndex === -1) {
      throw new ValidationError('Edit not found');
    }
    this._edits.splice(editIndex, 1);
  }

  _updateTitle(title) {
    if (!title || typeof title !== 'string' || title.trim() === '') {
      throw new ValidationError(
        'title is required and must be a non-empty string'
      );
    }
    this._title = title;
  }

  _updateContent(content) {
    if (content && typeof content !== 'string') {
      throw new ValidationError('content must be a string');
    }
    this._content = content || '';
  }

  _updateId(id) {
    // IMPORTANT: update id only for setting the id generated by the database
    // TODO IMPORTANT: find a way to avoid this method
    // It is marked as private to indicate it should not be used outside special cases
    if (!id || typeof id !== 'number') {
      throw new ValidationError('Script: id is required and must be a number');
    }
    this._id = id;
  }

  get id() {
    return this._id;
  }

  get content() {
    return this._content;
  }

  get createdAt() {
    return this._createdAt;
  }

  get title() {
    return this._title;
  }

  get userId() {
    return this._userId;
  }

  get edits() {
    return [...this._edits];
  }
}
