import { Script } from '../../domain/script/Script';
import { ValidationError } from '../../domain/common/errors';

export class CreateScript {
  constructor(scriptRepo) {
    this._scriptRepo = scriptRepo;
  }

  exec = async (script) => {
    if (!script)
      throw new ValidationError('CreateScript: An script is required');

    const newScriptData = { ...script };

    if (!newScriptData.id)
      newScriptData.id = await this._scriptRepo.nextId(newScriptData.userId);

    if (!script.createdAt) newScriptData.createdAt = new Date();

    const newScript = Script.create(newScriptData);

    // createdScript will contain the script with the id generated by the database
    const createdScript = await this._scriptRepo.save(newScript);

    return createdScript || newScript;
  };
}
