import { ValidationError } from '../common/errors';
import { EDIT_TYPES } from './editTypes';

export class Edit {
  constructor({ id, content, createdAt, type, isDone = false, scriptId }) {
    this._id = id;
    this._content = content;
    this._type = type;
    this._createdAt = createdAt;
    this._isDone = isDone;
    this._scriptId = scriptId;
  }

  static create({
    id,
    content = '',
    createdAt,
    type,
    isDone = false,
    scriptId,
  }) {
    if (!id) throw new ValidationError('Edit: id is required');
    if (typeof id !== 'number')
      throw new ValidationError('Edit: id must be a number');
    if (!createdAt) throw new ValidationError('Edit: createdAt is required');
    if (!type) throw new ValidationError('Edit: type is required');
    if (!scriptId) throw new ValidationError('Edit: scriptId is required');
    if (typeof scriptId !== 'number')
      throw new ValidationError('Edit: scriptId must be a number');

    if (!Object.values(EDIT_TYPES).includes(type))
      throw new ValidationError('Invalid edit type');

    if (!(createdAt instanceof Date) || isNaN(createdAt.getTime()))
      throw new ValidationError('Invalid createdAt');

    return new Edit({ id, content, createdAt, type, isDone, scriptId });
  }

  _updateContent(content) {
    if (content && typeof content !== 'string') {
      throw new ValidationError('content must be a string');
    }

    this._content = content || '';
  }

  _updateIsDone(isDone) {
    if (typeof isDone !== 'boolean') {
      throw new ValidationError('isDone must be a boolean');
    }

    this._isDone = isDone;
  }

  _updateType(type) {
    if (!Object.values(EDIT_TYPES).includes(type)) {
      throw new ValidationError('Invalid edit type');
    }

    this._type = type;
  }

  _updateId(id) {
    // IMPORTANT: update id only for setting the id generated by the database
    // TODO IMPORTANT: find a way to avoid this method
    // It is marked as private to indicate it should not be used outside special cases
    if (!id || typeof id !== 'number') {
      throw new ValidationError('id is required and must be a number');
    }
    this._id = id;
  }

  update({ content, isDone, type }) {
    if (content !== undefined) this._updateContent(content);
    if (isDone !== undefined) this._updateIsDone(isDone);
    if (type !== undefined) this._updateType(type);

    return this;
  }

  get id() {
    return this._id;
  }

  get content() {
    return this._content;
  }

  get type() {
    return this._type;
  }

  get createdAt() {
    return this._createdAt;
  }

  get isDone() {
    return this._isDone;
  }

  get scriptId() {
    return this._scriptId;
  }
}
